In [3]:
import pandas as pd

In [24]:
df_raw = pd.read_csv("./raw/movie_meta_last.csv", engine= "python")

In [3]:
df_raw.head()

,movie_id,title,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,imdb_score,votes,budget,...,contract_price,studio_score,price_class,language,awards,poster,metascore,release_dvd,reviews_users,reviews_critics
0,tt4154796,Avengers: Endgame,2019,26 Apr 2019,181.0,PG-13,.,8.5,"661,719",400000000,...,.,.,.,english,Nominated for 1 Oscar. Another 46 wins & 97 no...,https://m.media-amazon.com/images/M/MV5BMTc5MD...,78.0,30 Jul 2019,8538,543
1,tt1298650,Pirates of the Caribbean: On Stranger Tides,2011,20 May 2011,136.0,PG-13,.,6.6,"460,865",379000000,...,.,.,.,english,3 wins & 31 nominations.,https://m.media-amazon.com/images/M/MV5BMjE5Mj...,45.0,18 Oct 2011,524,465
2,tt2395427,Avengers: Age of Ultron,2015,01 May 2015,141.0,PG-13,.,7.3,"697,604",365000000,...,.,.,.,english,8 wins & 47 nominations.,https://m.media-amazon.com/images/M/MV5BMTM4OG...,66.0,02 Oct 2015,1276,688
3,tt4154756,Avengers: Infinity War,2018,27 Apr 2018,156.0,PG-13,.,8.5,"748,996",300000000,...,.,.,.,english,Nominated for 1 Oscar. Another 44 wins & 70 no...,https://m.media-amazon.com/images/M/MV5BMjMxNj...,68.0,14 Aug 2018,4158,601
4,tt0449088,Pirates of the Caribbean: At World's End,2007,25 May 2007,167.0,PG-13,.,7.1,"572,118",300000000,...,.,.,.,english,Nominated for 2 Oscars. Another 20 wins & 44 n...,https://m.media-amazon.com/images/M/MV5BMjIyNj...,50.0,04 Dec 2007,1275,326

In [5]:
for c in df_raw.columns : 
    nancount = len(df_raw[df_raw[c].isna()])
    dotcount = len(df_raw[df_raw[c]=="."])
    print("%s 결측치 개수 : %d, %d"%(c,nancount,dotcount))

movie_id 결측치 개수 : 0, 0
title 결측치 개수 : 0, 0
release_year 결측치 개수 : 0, 0
release_date 결측치 개수 : 67, 0
runtime 결측치 개수 : 36, 0
mpa_rating 결측치 개수 : 298, 0
mpa_rating_origin 결측치 개수 : 0, 5552
imdb_score 결측치 개수 : 125, 0
votes 결측치 개수 : 125, 0
budget 결측치 개수 : 0, 476
income_usa 결측치 개수 : 0, 492
income_int 결측치 개수 : 0, 1373

C:\Users\cresc\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

income_ww 결측치 개수 : 0, 1208
dvd_sales 결측치 개수 : 0, 3258
blu_sales 결측치 개수 : 0, 3913
total_sales 결측치 개수 : 0, 3913
income_opening 결측치 개수 : 0, 832
legs 결측치 개수 : 0, 715
share 결측치 개수 : 0, 492
inf_income_usa 결측치 개수 : 0, 675
theater_opening 결측치 개수 : 0, 836
theater_total 결측치 개수 : 0, 836
series 결측치 개수 : 0, 4474
genre 결측치 개수 : 9, 0
kwrds 결측치 개수 : 0, 1363
src 결측치 개수 : 0, 310
prd_mthd 결측치 개수 : 0, 256
creative_type 결측치 개수 : 0, 361
prd_company 결측치 개수 : 11, 1987
country 결측치 개수 : 8, 0
director 결측치 개수 : 66, 0
actor 결측치 개수 : 37, 0
writer 결측치 개수 : 151, 0
description 결측치 개수 : 115, 0
synop 결측치 개수 : 0, 102
contract_price 결측치 개수 : 0, 5552
studio_score 결측치 개수 : 0, 5552
price_class 결측치 개수 : 0, 5552
language 결측치 개수 : 3, 0
awards 결측치 개수 : 927, 0
poster 결측치 개수 : 157, 0
metascore 결측치 개수 : 932, 0
release_dvd 결측치 개수 : 522, 5
reviews_users 결측치 개수 : 227, 805
reviews_critics 결측치 개수 : 227, 830

In [4]:
df_raw['budget'].head()

0    400000000
1    379000000
2    365000000
3    300000000
4    300000000
Name: budget, dtype: object

In [12]:
df_bgt_empty = df_raw[df_raw['budget']=="."]

In [13]:
df_bgt_empty

,movie_id,title,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,imdb_score,votes,budget,...,contract_price,studio_score,price_class,language,awards,poster,metascore,release_dvd,reviews_users,reviews_critics
396,tt5697572,Cats,2019,20 Dec 2019,110 min,PG,.,2.8,"26,345",.,...,.,.,.,English,Nominated for 1 Golden Globe. Another 3 wins &...,https://m.media-amazon.com/images/M/MV5BNjRlNT...,32.0,NaN,NaN,NaN
646,tt6324278,Abominable,2019,27 Sep 2019,97 min,PG,.,7.0,"17,463",.,...,.,.,.,"English, Mandarin",3 wins & 20 nominations.,https://m.media-amazon.com/images/M/MV5BMTYzY2...,61.0,03 Dec 2019,NaN,NaN
1119,tt1206885,Rambo: Last Blood,2019,20 Sep 2019,89 min,R,.,6.2,"54,872",.,...,.,.,.,"English, Spanish",1 nomination.,https://m.media-amazon.com/images/M/MV5BNTAxZW...,26.0,NaN,NaN,NaN
1140,tt5478478,Hostiles,2017,26 Jan 2018,127.0,R,.,7.2,"59,715",.,...,.,.,.,english,4 wins & 7 nominations.,https://m.media-amazon.com/images/M/MV5BNjFhZj...,65.0,24 Apr 2018,401,184
1274,tt3513548,Richard Jewell,2019,13 Dec 2019,131 min,R,.,7.5,"17,389",.,...,.,.,.,English,Nominated for 1 Oscar. Another 5 wins & 11 nom...,https://m.media-amazon.com/images/M/MV5BOTFlOD...,68.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5547,tt5997666,Jab Harry Met Sejal,2017,04 Aug 2017,144.0,Not Rated,.,5.3,"17,380",.,...,.,.,.,hindi,6 wins & 8 nominations.,https://m.media-amazon.com/images/M/MV5BMjIzMD...,NaN,NaN,219,30
5548,tt5970844,Thugs of Hindostan,2018,08 Nov 2018,164.0,Not Rated,.,4.0,"16,245",.,...,.,.,.,hindi,1 win.,https://m.media-amazon.com/images/M/MV5BMTA3OD...,NaN,NaN,920,29
5549,tt5956100,Tiger Zinda Hai,2017,22 Dec 2017,145.0,Not Rated,.,6.0,"20,109",.,...,.,.,.,hindi,4 wins & 3 nominations.,https://m.media-amazon.com/images/M/MV5BYzM0ZT...,NaN,NaN,165,32
5550,tt5882970,Tubelight,2017,23 Jun 2017,170.0,Not Rated,.,4.0,"13,008",.,...,.,.,.,hindi,1 win & 3 nominations.,https://m.media-amazon.com/images/M/MV5BMjExNj...,NaN,NaN,123,28
5551,tt3405236,Raees,2017,25 Jan 2017,143 min,Not Rated,.,6.8,"37,898",.,...,.,.,.,Hindi,3 wins & 15 nominations.,https://m.media-amazon.com/images/M/MV5BMTc2NT...,NaN,NaN,194,43

In [11]:
df_raw.loc[df_raw['movie_id'] == "tt5814534", 'budget'] = 100000000

df_raw[df_raw['movie_id']=="tt5814534"]

,movie_id,title,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,imdb_score,votes,budget,...,contract_price,studio_score,price_class,language,awards,poster,metascore,release_dvd,reviews_users,reviews_critics
380,tt5814534,Spies in Disguise,2019,25 Dec 2019,102 min,PG,.,6.8,"6,648",100000000,...,.,.,.,"English, Japanese",3 nominations.,https://m.media-amazon.com/images/M/MV5BNzg1Mz...,54.0,NaN,NaN,NaN

In [9]:
df_raw[df_raw['movie_id'] == 'tt5814534']

,movie_id,title,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,imdb_score,votes,budget,...,contract_price,studio_score,price_class,language,awards,poster,metascore,release_dvd,reviews_users,reviews_critics
380,tt5814534,Spies in Disguise,2019,25 Dec 2019,102 min,PG,.,6.8,"6,648",.,...,.,.,.,"English, Japanese",3 nominations.,https://m.media-amazon.com/images/M/MV5BNzg1Mz...,54.0,NaN,NaN,NaN

In [16]:
from bs4 import BeautifulSoup
import requests
import re

df_bgt_empty = df_raw[df_raw['budget'] == "."]

movie_id = df_bgt_empty['movie_id']

for i in movie_id:
    url = "https://www.imdb.com/title/{}/".format(i)
    resp = requests.get(url)
    html = resp.text
    soup = BeautifulSoup(html, "html5lib")
    tags_budget = soup.select("#titleDetails > div:nth-child(12) > h4")

    text_budget = ""
    for tag in tags_budget:
        text_budget += tag.text
    p = re.findall(r'\d+', text_budget)
    p = ''.join(p)
    if text_budget == '':
        df_raw.loc[df_raw['movie_id'] == i, 'budget'] = '.'
    else:
        df_raw.loc[df_raw['movie_id'] == i, 'budget'] = p

KeyboardInterrupt:

In [20]:
from bs4 import BeautifulSoup
import requests
import re

df_bgt_empty = df_raw[df_raw['budget'] == "."]

movie_id = df_bgt_empty['movie_id']

# for i in movie_id:
i = 'tt0102782'
url = "https://www.imdb.com/title/{}/".format(i)
resp = requests.get(url)
html = resp.text
soup = BeautifulSoup(html, "html5lib")
tags_budget = soup.select("#titleDetails > div:nth-child(12)")

print(tags_budget)
text_budget = ""
for tag in tags_budget:
    text_budget += tag.text
p = re.findall(r'\d+', text_budget)
p = ''.join(p)
if text_budget == '':
    df_raw.loc[df_raw['movie_id'] == i, 'budget'] = '.'
else:
    df_raw.loc[df_raw['movie_id'] == i, 'budget'] = p
    
df_raw[df_raw['movie_id'] == i]

[<div class="txt-block">
            <h4 class="inline">Budget:</h4>$11,000,000
            <span class="attribute">(estimated)</span>
        </div>]

,movie_id,title,release_year,release_date,runtime,mpa_rating,mpa_rating_origin,imdb_score,votes,budget,...,contract_price,studio_score,price_class,language,awards,poster,metascore,release_dvd,reviews_users,reviews_critics
3302,tt0102782,Return to the Blue Lagoon,1991,02 Aug 1991,102 min,PG-13,.,5.2,"17,196",11000000,...,.,.,.,English,6 nominations.,https://m.media-amazon.com/images/M/MV5BMTM1Mz...,NaN,05 Nov 2002,44,13

In [23]:
for i in movie_id:
    print(i)

tt0081059
tt4682804
tt1798603
tt4916630
tt2461150
tt8367814
tt2872518
tt3361792
tt1838544
tt0107719
tt1478839
tt8332922
tt8385474
tt7734218
tt2935476
tt7798646
tt7083526
tt4126476
tt0077296
tt0859635
tt7329656
tt7390646
tt0077269
tt7510346
tt0059113
tt5362988
tt0072684
tt0066090
tt5563334
tt5125894
tt9173418
tt6521876
tt5886046
tt4913966
tt8772262
tt2354181
tt7489740
tt0102915
tt0074812
tt4131800
tt4364194
tt7798634
tt1489887
tt7339792
tt0107750
tt2932536
tt9086228
tt9354944
tt6511932
tt1730760
tt7984734
tt0092615
tt0074958
tt0081617
tt0077362
tt6113488
tt0067065
tt1264890
tt0069768
tt0106792
tt0045793
tt0063592
tt0074225
tt0108000
tt0076271
tt0104567
tt0102989
tt0081114
tt0092548
tt0079062
tt0074486
tt0484562
tt0371257
tt0457419
tt0455967
tt0430779
tt0388125
tt1336006
tt2625810
tt4721124
tt4846232
tt3859310
tt2034031
tt4385888
tt2132285
tt2326612
tt2402101
tt6040662
tt6902696
tt5691670
tt5715874
tt4827558
tt5613484
tt1727770
tt0401420
tt0374563
tt0475937
tt1313139
tt1166100
tt2788716
tt2334733
tt5742374
tt2141751
tt1763264
tt0497972
tt1037218
tt2980472
tt5884230
tt3480796
tt2368254
tt2062700
tt2101383
tt3062976
tt2891174
tt4679210
tt1667321
tt4669264
tt4899370
tt6225520
tt6108178
tt5023260
tt1596345
tt0402894
tt0480242
tt0465234
tt0997047
tt0435670
tt1185416
tt0417433
tt0772193
tt1093908
tt0452681
tt0396555
tt0467110
tt3442006
tt2370248
tt0780595
tt5071886
tt0401815
tt1858481
tt2215395
tt2488778
tt4009278
tt5270948
tt2390237
tt3203528
tt4399952
tt2317337
tt3735246
tt1188982
tt8108198
tt1255951
tt4110568
tt0806088
tt1144804
tt2140465
tt5859238
tt6971752
tt1891757
tt2172071
tt4559046
tt2309764
tt0991346
tt1395025
tt5197544
tt0488414
tt3679060
tt5474036
tt3678782
tt2806788
tt2639254
tt2758904
tt2172584
tt2091935
tt6277440
tt3595298
tt6988116
tt2905838
tt4169250
tt3142688
tt6843812
tt7255568
tt4559006
tt5286444
tt6452574
tt3754940
tt4853102
tt0473488
tt8695030
tt4572792
tt0970468
tt2261331
tt0400525
tt0427969
tt0810819
tt0796368
tt1234654
tt0116684
tt1229822
tt2639336
tt2218003
tt4731136
tt2799166
tt2226597
tt1502712
tt1172049
tt3387266
tt2837574
tt0267891
tt2872462
tt0838221
tt2273657
tt0975645
tt2056771
tt1781058
tt0145503
tt5977276
tt0808331
tt1606392
tt2112096
tt1710417
tt0790804
tt5669936
tt2784512
tt4669296
tt5666304
tt4799066
tt1183374
tt2511428
tt1082853
tt0841044
tt0275230
tt6980546
tt1407084
tt0352994
tt0454776
tt1226774
tt4686844
tt3463106
tt2944198
tt1067765
tt0989000
tt3577624
tt1183665
tt4714782
tt3297330
tt4977530
tt1487118
tt1320239
tt5195412
tt0420293
tt1853643
tt3208026
tt2674430
tt7026672
tt1433811
tt2626350
tt7242142
tt4382872
tt2490326
tt1767372
tt0376479
tt3797868
tt0475355
tt2378507
tt0443473
tt2235779
tt0800003
tt6018306
tt1389096
tt0492044
tt5670152
tt0870211
tt0361693
tt0426615
tt1521848
tt0800027
tt0780571
tt5208252
tt0489237
tt1932767
tt4383594
tt4126438
tt3824458
tt2870808
tt2393845
tt5886440
tt1783732
tt1133993
tt1278449
tt5989218
tt1247690
tt1045670
tt0858479
tt0427470
tt0488120
tt0433400
tt0091875
tt0768212
tt0419984
tt4334266
tt5962210
tt2883512
tt1850397
tt5655222
tt3203620
tt6212478
tt1046947
tt0408236
tt0408839
tt0815245
tt0477051
tt1130988
tt8291224
tt4943322
tt0757361
tt4530422
tt0110684
tt0491175
tt0404802
tt0494834
tt5607096
tt1164999
tt4291600
tt4258698
tt0460890
tt0460791
tt3068194
tt0903657
tt3168230
tt1720616
tt1368440
tt5628302
tt1528071
tt0830570
tt4934950
tt4814290
tt1806913
tt2339741
tt3173910
tt2356180
tt7212726
tt1729637
tt0315642
tt7485048
tt5946128
tt0456020
tt0424823
tt0452702
tt0110889
tt0486578
tt7668870
tt2624412
tt2097331
tt5304464
tt5164184
tt4326444
tt0411195
tt4048272
tt2870756
tt1023441
tt1969062
tt0364955
tt0790770
tt1490785
tt3715320
tt6217608
tt3721964
tt1661275
tt5789976
tt4005402
tt0349467
tt0457433
tt0422774
tt0080923
tt0113755
tt0897361
tt0395495
tt0838232
tt0139151
tt7074886
tt6905696
tt1530983
tt1146325
tt0804516
tt4437216
tt4104022
tt3774466
tt0803057
tt0370986
tt1321511
tt0292963
tt0097790
tt0444653
tt3416742
tt6348138
tt4864932
tt4535650
tt4129428
tt3859980
tt3554418
tt3390572
tt3148502
tt2344678
tt0449994
tt2112124
tt1934231
tt1734110
tt1375789
tt4682788
tt1084972
tt0343737
tt0113537
tt0387514
tt0384793
tt0426883
tt8085790
tt8079248
tt6921996
tt6911608
tt0082801
tt2616810
tt2397535
tt2012011
tt2395469
tt7721800
tt0808399
tt4468740
tt0093793
tt0450345
tt0956038
tt1951261
tt0486583
tt0821640
tt4443658
tt0119167
tt1172991
tt2070776
tt1800302
tt1686821
tt6173990
tt0110678
tt1786751
tt0432289
tt5108476
tt0375611
tt1182937
tt3767372
tt3495026
tt1740710
tt7431594
tt6836936
tt6588966
tt6527426
tt5997666
tt5970844
tt5956100
tt5882970
tt3405236

In [25]:
df_bgt_empty = df_raw[df_raw['budget'] == "."]
movie_id = df_bgt_empty['movie_id']

i = 0
for ids in movie_id:
    try:
        i += 1
        print(i)
        url = "https://www.imdb.com/title/{}/".format(ids)
        resp = requests.get(url)
        html = resp.text
        soup = BeautifulSoup(html, "html5lib")
        tags_budget = soup.select("#titleDetails > div:nth-child(12)")

        text_budget = ""
        for tag in tags_budget:
            text_budget += tag.text
        p = re.findall(r'\d+', text_budget)
        p = ''.join(p)
        if text_budget == '':
            df_raw.loc[df_raw['movie_id'] == ids, 'budget'] = '.'
        else:
            df_raw.loc[df_raw['movie_id'] == ids, 'budget'] = p
    except:
        print(ids)

df_raw.loc[df_raw['movie_id'] == "tt0081059", 'budget'] = 35000000
df_raw.loc[df_raw['movie_id'] == "tt0077269", 'budget'] = 12000000
df_raw.loc[df_raw['movie_id'] == "tt0066090", 'budget'] = 11000000
df_raw.loc[df_raw['movie_id'] == "tt7489740", 'budget'] = '.'
df_raw.loc[df_raw['movie_id'] == "tt0074812", 'budget'] = 9000000
df_raw.loc[df_raw['movie_id'] == "tt1730760", 'budget'] = 4500000
df_raw.loc[df_raw['movie_id'] == "tt0081617", 'budget'] = 3500000
df_raw.loc[df_raw['movie_id'] == "tt0106792", 'budget'] = 1800000
df_raw.loc[df_raw['movie_id'] == "tt0063592", 'budget'] = 1455000
df_raw.loc[df_raw['movie_id'] == "tt0074225", 'budget'] = 12000000
df_raw.loc[df_raw['movie_id'] == "tt0076271", 'budget'] = 500000
df_raw.loc[df_raw['movie_id'] == "tt0081114", 'budget'] = 350000
df_raw.loc[df_raw['movie_id'] == "tt0079062", 'budget'] = 170000
df_raw.loc[df_raw['movie_id'] == "tt0275230", 'budget'] = '.'
df_raw.loc[df_raw['movie_id'] == "tt5164184", 'budget'] = '.'
df_raw.loc[df_raw['movie_id'] == "tt0080923", 'budget'] = 3000000
df_raw.loc[df_raw['movie_id'] == "tt0139151", 'budget'] = 15000000
df_raw.loc[df_raw['movie_id'] == "tt0119167", 'budget'] = '.'
df_raw.loc[df_raw['movie_id'] == "tt6173990", 'budget'] = ''


print(df_raw['budget'])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
0        400000000
1        379000000
2        365000000
3        300000000
4        300000000
           ...
5547       1664648
5548      20000000
5549      20470000
5550    1550000000
5551       3262954
Name: budget, Length: 5552, dtype: object

In [26]:
df_raw.to_csv('./raw/temp.csv', header=True, index=False)

In [46]:
a = df_raw.loc[5002:]['movie_id']

b = df_raw.loc[500:600]['movie_id']

In [48]:
a.append(b)

5002    tt0484562
5003    tt0371257
5004    tt0980970
5005    tt0936501
5006    tt1396218
          ...
596     tt0300556
597     tt1723746
598     tt0120595
599     tt0119925
600     tt0199753
Name: movie_id, Length: 651, dtype: object

In [51]:
a

5002    tt0484562
5003    tt0371257
5004    tt0980970
5005    tt0936501
5006    tt1396218
          ...
5547    tt5997666
5548    tt5970844
5549    tt5956100
5550    tt5882970
5551    tt3405236
Name: movie_id, Length: 550, dtype: object

In [52]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re



df_raw = pd.read_csv('./raw/movie_meta_last.csv', engine='python')


#    변수명 : budget  /  공유 파일 이름 : xxx
#    budget 웬만하면 numbers랑 imdb에 다 있는데 왜 안들어 온게 400개나 있는지 모르겠음.
#    scrapping해서 채워 넣음(IMDB 기준, IMDB에 없는 경우 the numbers 참고하였음)
#    밀려서 들어온 데이터 : tt1781967, tt2367359, tt0387898, tt7017420, tt4950016, tt7048386, tt1587396, tt0498879, tt4403432, tt2010510
#    0이 3개 빠진 듯한 데이터들이 좀 있는데, 그런 관측치는 다른 값들도 없어서 어차피 삭제될 거라 가정하고 수정하지 않음.

def budget(df_raw):
    df_bgt_empty = df_raw[df_raw['budget'] == "."]
    movie_id = df_bgt_empty['movie_id']
    movie_id = movie_id.append(df_raw.loc[5002:]['movie_id'])

    i = 0
    for ids in movie_id:
        try:
            i += 1
            print(i)
            url = "https://www.imdb.com/title/{}/".format(ids)
            resp = requests.get(url)
            html = resp.text
            soup = BeautifulSoup(html, "html5lib")
            tags_budget = soup.select("#titleDetails > div:nth-child(12)")

            text_budget = ""
            for tag in tags_budget:
                text_budget += tag.text
            p = re.findall(r'\d+', text_budget)
            p = ''.join(p)
            if text_budget == '':
                df_raw.loc[df_raw['movie_id'] == ids, 'budget'] = '.'
            else:
                df_raw.loc[df_raw['movie_id'] == ids, 'budget'] = p
        except:
            print(ids)

    df_raw.loc[df_raw['movie_id'] == "tt0081059", 'budget'] = 35000000
    df_raw.loc[df_raw['movie_id'] == "tt0077269", 'budget'] = 12000000
    df_raw.loc[df_raw['movie_id'] == "tt0066090", 'budget'] = 11000000
    df_raw.loc[df_raw['movie_id'] == "tt7489740", 'budget'] = '.'
    df_raw.loc[df_raw['movie_id'] == "tt0074812", 'budget'] = 9000000
    df_raw.loc[df_raw['movie_id'] == "tt1730760", 'budget'] = 4500000
    df_raw.loc[df_raw['movie_id'] == "tt0081617", 'budget'] = 3500000
    df_raw.loc[df_raw['movie_id'] == "tt0106792", 'budget'] = 1800000
    df_raw.loc[df_raw['movie_id'] == "tt0063592", 'budget'] = 1455000
    df_raw.loc[df_raw['movie_id'] == "tt0074225", 'budget'] = 12000000
    df_raw.loc[df_raw['movie_id'] == "tt0076271", 'budget'] = 500000
    df_raw.loc[df_raw['movie_id'] == "tt0081114", 'budget'] = 350000
    df_raw.loc[df_raw['movie_id'] == "tt0079062", 'budget'] = 170000
    df_raw.loc[df_raw['movie_id'] == "tt0275230", 'budget'] = '.'
    df_raw.loc[df_raw['movie_id'] == "tt5164184", 'budget'] = '.'
    df_raw.loc[df_raw['movie_id'] == "tt0080923", 'budget'] = 3000000
    df_raw.loc[df_raw['movie_id'] == "tt0139151", 'budget'] = 15000000
    df_raw.loc[df_raw['movie_id'] == "tt0119167", 'budget'] = '.'
    df_raw.loc[df_raw['movie_id'] == "tt6173990", 'budget'] = ''
    df_raw.loc[df_raw['movie_id'] == "tt5851562", 'budget'] = 350000
    df_raw.loc[df_raw['movie_id'] == "tt6324278", 'budget'] = 75000000
    df_raw.loc[df_raw['movie_id'] == "tt4682804", 'budget'] = 27000000
    df_raw.loc[df_raw['movie_id'] == "tt1838544", 'budget'] = 19000000
    df_raw.loc[df_raw['movie_id'] == "tt0107719", 'budget'] = 19000000
    df_raw.loc[df_raw['movie_id'] == "tt8332922", 'budget'] = 17000000
    df_raw.loc[df_raw['movie_id'] == "tt0077296", 'budget'] = 14000000
    df_raw.loc[df_raw['movie_id'] == "tt7329656", 'budget'] = 12000000
    df_raw.loc[df_raw['movie_id'] == "tt7510346", 'budget'] = 14000000
    df_raw.loc[df_raw['movie_id'] == "tt0072684", 'budget'] = 11000000
    df_raw.loc[df_raw['movie_id'] == "tt6521876", 'budget'] = 10000000
    df_raw.loc[df_raw['movie_id'] == "tt2354181", 'budget'] = 89500000 # 가장 가까운 데이터 90000000, 89000000 의 평균값으로 대체
    df_raw.loc[df_raw['movie_id'] == "tt7339792", 'budget'] = 6000000
    df_raw.loc[df_raw['movie_id'] == "tt7984734", 'budget'] = 4000000
    df_raw.loc[df_raw['movie_id'] == "tt0092615", 'budget'] = 4000000
    df_raw.loc[df_raw['movie_id'] == "tt0074958", 'budget'] = 3800000
    df_raw.loc[df_raw['movie_id'] == "tt0077362", 'budget'] = 3000000
    df_raw.loc[df_raw['movie_id'] == "tt6113488", 'budget'] = 5000000
    df_raw.loc[df_raw['movie_id'] == "tt0045793", 'budget'] = 1650000
    df_raw.loc[df_raw['movie_id'] == "tt0108000", 'budget'] = 800000
    df_raw.loc[df_raw['movie_id'] == "tt0104567", 'budget'] = 500000
    df_raw.loc[df_raw['movie_id'] == "tt0102989", 'budget'] = 450000
    df_raw.loc[df_raw['movie_id'] == "tt0092548", 'budget'] = 350000
    df_raw.loc[df_raw['movie_id'] == "tt0068468", 'budget'] = 25000
    df_raw.loc[df_raw['movie_id'] == "tt0074486", 'budget'] = 20000



budget(df_raw)
df_raw.to_csv('./raw/temp1.csv', header=True, index=False)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026

In [55]:
df_raw[df_raw['series'].isna() == True]

Empty DataFrame
Columns: [movie_id, title, release_year, release_date, runtime, mpa_rating, mpa_rating_origin, imdb_score, votes, budget, income_usa, income_int, income_ww, dvd_sales, blu_sales, total_sales, income_opening, legs, share, inf_income_usa, theater_opening, theater_total, series, genre, kwrds, src, prd_mthd, creative_type, prd_company, country, director, actor, writer, description, synop, contract_price, studio_score, price_class, language, awards, poster, metascore, release_dvd, reviews_users, reviews_critics]
Index: []

[0 rows x 45 columns]

In [66]:
df_raw.loc[df_raw['series'] == '.', 'series_new'] = 0
df_raw.loc[df_raw['series'] != '.', 'series_new' ] = 1

In [67]:
df_raw['series_new'].astype('int')

0       1
1       1
2       1
3       1
4       1
       ..
5547    0
5548    0
5549    0
5550    0
5551    0
Name: series_new, Length: 5552, dtype: int32

In [ ]:
##### 이따 돌릴것


df_raw = pd.read_csv("./raw/movie_meta_last.csv", engine= "python")

movie_id = df_raw['movie_id']

i = 0
for ids in movie_id:
    try:
        i += 1
        print(i)
        url = "https://www.imdb.com/title/{}/keywords?ref_=ttpl_ql_4".format(ids)
        resp = requests.get(url)
        html = resp.text
        soup = BeautifulSoup(html, "html5lib")
        tags_kwrds = soup.select("#keywords_content > table > tbody > tr > td > div.sodatext")
        
        text_kwrds = ""
        for tag in tags_kwrds:
            text_kwrds += tag.text
        if text_budget == '':
            df_raw.loc[df_raw['movie_id'] == ids, 'kwrds'] = '.'
        else:
            df_raw.loc[df_raw['movie_id'] == ids, 'kwrds'] = p
    except:
        print(ids)
        
df_raw.to_csv('./raw/temp_kwrds.csv', header=True, index=False)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
tt1386703
282
283
284
285
286
287
288
289
tt0454876
290
291
292
293
294
295
296
297
298
299
300
tt0811080
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
tt2283336
328
329
330
331
332
333

In [ ]:
df_raw['creative_type']